[33m467422c[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mrevive-467422c[m[33m, [m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m, [m[1;32mmain[m[33m)[m feat: Add comprehensive architecture audit and Cursor Rules (CR.md)
 CHANGELOG.md           |  21 [32m++[m[31m-[m
 CR.md                  | 355 [32m+++++++++++++++++++++++++++++++++++++++++++++[m
 Data/SavedNote.cs      |  11 [32m++[m
 FEATURES_TO_ADD.md     |   3 [32m+[m[31m-[m
 MainWindow.xaml.cs     |  62 [32m++++++++[m
 NoteTab.xaml.cs        |  11 [32m+[m[31m-[m
 THOUGHTS.md            |   1 [32m+[m
 UI/KeyboardHandler.cs  |  67 [32m+++++++++[m
 UI/TabManager.cs       |  13 [32m+[m[31m-[m
 UI/TextSection.xaml    |  41 [32m+++[m[31m---[m
 UI/TextSection.xaml.cs | 387 [32m++++++++++++++++++++++++++++++++++++++++++++++[m[31m---[m
 11 files changed, 926 insertions(+), 46 deletions(-)
[33m5666a23[m initial commit for snipshottyboard wpf net 8 app
 .cursorrules                                       |  171 [32m+++[m
 .gitignore                                         |   38 [32m+[m
 AGENT_GUIDE.md                                     |  120 [32m++[m
 App.xaml                                           |   15 [32m+[m
 App.xaml.cs                                        |   41 [32m+[m
 AssemblyInfo.cs                                    |   10 [32m+[m
 CHANGELOG.md                                       |   72 [32m++[m
 Data/AppData.cs                                    |   43 [32m+[m
 Data/AppSettings.cs                                |  168 [32m+++[m
 Data/DataManager.cs                                |  258 [32m+++++[m
 Data/NoteWindowManager.cs                          |  115 [32m++[m
 Data/SavedNote.cs                                  |   92 [32m++[m
 Examples/MediaSectionRefactored.cs                 |  331 [32m++++++[m
 FEATURES_TO_ADD.md                                 |  161 [32m+++[m
 MainWindow.xaml                                    |  205 [32m++++[m
 MainWindow.xaml.cs                                 |  583 [32m++++++++++[m
 NoteTab.xaml                                       |   99 [32m++[m
 NoteTab.xaml.cs                                    |  210 [32m++++[m
 README.md                                          |  100 [32m++[m
 SettingsWindow.xaml                                |  421 [32m+++++++[m
 SettingsWindow.xaml.cs                             |  468 [32m++++++++[m
 SnipShottyBoard.csproj                             |   18 [32m+[m
 SnipShottyBoard_Roadmap.txt                        |  301 [32m+++++[m
 THOUGHTS.md                                        |    0
 Themes/DarkTheme.xaml                              |  749 [32m+++++++++++++[m
 Themes/LightTheme.xaml                             |  749 [32m+++++++++++++[m
 UI/CustomDialog.xaml                               |  127 [32m+++[m
 UI/CustomDialog.xaml.cs                            |  227 [32m++++[m
 UI/CustomInputDialog.xaml                          |  154 [32m+++[m
 UI/CustomInputDialog.xaml.cs                       |  186 [32m++++[m
 UI/CustomTab.cs                                    |   21 [32m+[m
 UI/DialogHelper.cs                                 |  298 [32m+++++[m
 UI/EventHelper.cs                                  |  264 [32m+++++[m
 UI/HelpManager.cs                                  |  359 [32m++++++[m
 UI/ImageViewerWindow.xaml                          |  221 [32m++++[m
 UI/ImageViewerWindow.xaml.cs                       |  537 [32m+++++++++[m
 UI/KeyboardHandler.cs                              |  148 [32m+++[m
 UI/LoggingService.cs                               |   38 [32m+[m
 UI/MediaSection.xaml                               |   45 [32m+[m
 UI/MediaSection.xaml.cs                            | 1153 [32m++++++++++++++++++++[m
 UI/NoteListWindow.xaml                             |  111 [32m++[m
 UI/NoteListWindow.xaml.cs                          |  368 [32m+++++++[m
 UI/ResourceHelper.cs                               |  126 [32m+++[m
 UI/SafeExecutionHelper.cs                          |   99 [32m++[m
 UI/SettingsManager.cs                              |  133 [32m+++[m
 UI/StatusBarManager.cs                             |   59 [32m+[m
 UI/TabManager.cs                                   | 1108 [32m+++++++++++++++++++[m
 UI/TextSection.xaml                                |   48 [32m+[m
 UI/TextSection.xaml.cs                             |  139 [32m+++[m
 UI/ThemeManager.cs                                 |   90 [32m++[m
 UI/UIFactory.cs                                    |  312 [32m++++++[m
 mcp-servers/SNIPSHOTTYBOARD-SETUP.md               |  125 [32m+++[m
 .../claude_desktop_config_snipshottyboard.json     |   11 [32m+[m
 mcp-servers/package.json                           |    9 [32m+[m
 mcp-servers/run-snipshottyboard-mcp.bat            |    5 [32m+[m
 mcp-servers/snipshottyboard-mcp.js                 |  688 [32m++++++++++++[m
 56 files changed, 12747 insertions(+)
